services:
  ponderada:
    image: metabase/metabase
    ports:
      - "3000:3000"
    volumes:
      - ./database:/ponderada5
    container_name: ponderada5-felipe
    environment:
      - BROKER_ADDRS=6426734a3da84d93b3baa50505326709.s1.eu.hivemq.cloud
      - HIVE_USER=Felipe
      - HIVE_PSWD=Admin12345