name: Testes automatizados
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      USERNAME_SECRET: ${{ secrets.USERNAME_SECRET }}
      PASSWORD_SECRET: ${{ secrets.PASSWORD_SECRET }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Go test
        run: cd ponderada4/main && go test -v
