name: Testes automatizados
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Go test
        run: cd ponderada4/main && go test -v
