name: Testes automatizados
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      USERNAME_SECRET: ${{ secrets.USERNAME_SECRET }}
      PASSWORD_SECRET: ${{ secrets.PASSWORD_SECRET }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env
        working-directory: ponderada4
        run: 
          touch .env
          echo "BROKER_ADDR=${{ secrets.BROKER_ADDR_SECRET }}" >> .env
          echo "USERNAME=${{ secrets.USERNAME_SECRET }}" >> .env
          echo "PASSWORD=${{ secrets.PASSWORD_SECRET }}" >> .env

      - name: Go test
        working-directory: ponderada4/main
        run: 
          go test -v

